# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    container_name: postgres-docker
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./postgres-docker:/var/lib/postgres
