version: "3"

services:
  postgres:
    container_name: postgres-docker
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users
    volumes:
      - ./data/postgres-docker:/data/postgres
    ports:
      - "5432:5432"
