version: "3"

services:
  postgres:
    container_name: postgres-docker
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users
    volumes:
      - ./data/postgres-docker:/data/postgres
    ports:
      - "5432:5432"
  servidor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: sh -c "sleep 5 && npx prisma migrate dev --name users && npm start"
